### PR TITLE
Adds try/catch to the ESLint processor preprocess task

### PR DESCRIPTION
**Pull request by therealgilles**
## Description
Adds try/catch to the ESLint processor preprocess task, to bail and return the original code if an error is thrown by the underlying parser (e.g. a parsing error outside the template strings).

The ESLint crew told me processors are not supposed to throw errors. See discussion here: https://github.com/eslint/eslint/discussions/16015

Fixes [# (issue)](https://github.com/B2o5T/graphql-eslint/issues/1092)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots/Sandbox (if appropriate/relevant):
Here is a simple repo that reproduces the issue: https://github.com/therealgilles/graphql-config-code-file-ts

## How Has This Been Tested?
I'm not sure how to build the repo and run existing tests. If you have documentation on this, I'll be happy to do it.

**Test Environment**:

- OS: MacOS Ventura 13.0 Beta
- `@graphql-eslint/...`: 3.10.4
- NodeJS: v16.15.0

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests and linter rules pass locally with my changes
- [N/A] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by JounQin** [comment]
An error indicate bug, you should never suppress unexpected errors.

**Comment by therealgilles** [comment]
@JounQin The syntax error will be reported by ESLint so it will be caught.

Ideally @babel/parser would be called with the ErrorRecovery flag set to true. But graphql-tag-pluck does not seem to give any control on that. Additionally it's not clear that this would be enough in all parsing error cases.

I think the right thing to do is to suppress the error so that ESLint can proceed and the syntax error can be reported. I would add a warning message when running ESLint in debug mode, so that debugging is easier.

**Comment by JounQin** [comment]
This is similar situation for all processors.

If the syntax is correct, then it's a bug of this plugin.

If the syntax is incorrect, then a clearer crash error should help the user to understand.

Maybe ESLint should support `SyntaxError` with `loc` info from processors. (This is a ESLint proposal, if your description from ESLint team's view is correct.)

**Comment by therealgilles** [comment]
See ESLint discussion here: https://github.com/eslint/eslint/discussions/16015#discussioncomment-3028452

**Comment by JounQin** [comment]
> See ESLint discussion here: [eslint/eslint#16015 (reply in thread)](https://github.com/eslint/eslint/discussions/16015#discussioncomment-3028452)

So if I don't understand incorrectly, @btmills agree to `try/catch` in ESLint's `process` logic instead of handling it by processor itself?

https://github.com/eslint/eslint/discussions/16015#discussioncomment-3028452

**Comment by therealgilles** [comment]
I think it is under consideration. I still think it's bad form for a preprocessor to throw, but not sure how preprocessor would be intended to report errors to ESLint core.

**Comment by dotansimha** [comment]
@B2o5T what do you think?

**Comment by JounQin** [comment]
See https://github.com/eslint/eslint/issues/16104 and my PR https://github.com/eslint/eslint/pull/16105

**Comment by B2o5T** [comment]
Sorry for the long response, closing it here since this will be fixed in ESLint directly

**Pull request closed without merging**
